### ISSUE TITLE
Have you seen this trove of fonts?

### ISSUE THREAD

**Issue by drudru** [robhagemans/hoard-of-bitfonts#1]
https://www.lyonlabs.org/commodore/onrequest/geos/geos-fonts.html

There is a link in there under 'explore it' to here: 
https://www.lyonlabs.org/geofont/

**Comment by robhagemans** [comment]
Ah, these bring back memories... Turns out I had them in my list somewhere - but there is always too much to do :(

**Comment by drudru** [comment]
No worries - just wanted to make sure you were aware of them :+1:
