### ISSUE TITLE
Off-by-two (rows) error in msx_kr.draw

### ISSUE THREAD

**Issue by kfitch** [robhagemans/hoard-of-bitfonts#2]
There seems to be an off-by-two (rows) error in msx_kr.draw. This is most obvious looking at entry 0d which appears to be a capital X, but the last two rows ended up in entry 0e. I am pretty sure this error applies to every single character in the font.

**Comment by robhagemans** [comment]
Thanks for reporting this, this has been fixed by uploading a new file `msx-kr.yaff`.
