### ISSUE TITLE
Missing pixel

### ISSUE THREAD

**Issue by MarkJeronimus** [robhagemans/hoard-of-bitfonts#20]
I think I spotted a missing pixel in box character ┤. If this was a thing, I would've seen discontinuous boxes in dos when I had my EGA computer. Do you have any verifiable source for this font?

https://github.com/robhagemans/hoard-of-bitfonts/blob/174f3384cbdf72d77b621944bd69f6623d09ee79/windows/windows-3.1/Terminal_EGA80_cp850.yaff#L3003

**Comment by robhagemans** [comment]
This comes off the Windows 3.1 installation disks. DOS would have used the
BIOS font or a CPI, not a Windows .FON file, so it makes sense that you
didn't see this in DOS.
