### ISSUE TITLE
These are not Windows fonts.

### ISSUE THREAD

**Issue by MarkJeronimus** [robhagemans/hoard-of-bitfonts#21]
Fonts like https://github.com/robhagemans/hoard-of-bitfonts/blob/174f3384cbdf72d77b621944bd69f6623d09ee79/windows/windows-3.1/Terminal_EGA80_cp850.yaff are not Windows fonts, yet they are categorized under 'Windows'.

They're at best DOS fonts, but actually they're stored in BIOS ROM, and optionally overridden by code page files in DOS. Windows, up to 3.11, was an 'application' that runs on DOS, and iirc, doesn't even show the DOS fonts graphically.

Fonts stored in the BIOS were most often (in the west at least) IBM fonts.

**Comment by robhagemans** [comment]
These were supplied with Windows, hence categorised there. I got them off
Windows distribution disks.
