### ISSUE TITLE
HP 1660, 16500 etc logic analyzer font 

### ISSUE THREAD

**Issue by fenugrec** [robhagemans/hoard-of-bitfonts#25]
Hi,
if you're interested, attached are two bitmap fonts used on a very large familiy of HP logic analyzers of the 90's. They run X11 and use these fonts directly, which one would need to copy at the 'server' end when using a remote X session to control these machines.

[HP_165.zip](https://github.com/robhagemans/hoard-of-bitfonts/files/11113748/HP_165.zip)

**Comment by robhagemans** [comment]
Thanks! - do you have any links or background to these machines? The stuff a Google search throws up is all a bit confusing...

**Comment by fenugrec** [comment]
Of course.

Official product pages : (this division of HP became Agilent and now Keysight)
https://www.keysight.com/us/en/product/1660CS/136channel-100mhz-state500mhz-benchtop-la.html
https://www.keysight.com/us/en/product/16500B/logic-analysis-system-mainframe.html

A more general overview of logic analyzers, in case you aren't already familiar :
	https://en.wikipedia.org/wiki/Logic_analyzer

So, to summarize - it's electronics test equipment, obsolete but still usable when reparing and working on also-obsolete equipment.

**Comment by robhagemans** [comment]
Thanks, I included them. This exposed a bug in my BDF converter - the "small" font is 8-pixels wide but defines its glyphs with 2 bytes per line, for some reason, which the converter couldn't deal with correctly. Fixed now.
