### ISSUE TITLE
HP 4195A 8x13 font

### ISSUE THREAD

**Issue by fenugrec** [robhagemans/hoard-of-bitfonts#26]
This font is extracted from a ROM dump, Rev 2.00 (datecode 03/1989), of an HP 4195A network/spectrum analyzer.

 Characters 0x20-0x7F are essentially ASCII. 00-0x1F are special characters; many are simply empty space.
 The ROM uses a lookup table which maps all these unused characters to the same "space" bitmap.
 In addition, they are drawn LSB-to-MSB which made it necessary to mirror the whole font.

![hp4195_8x13_remapped](https://user-images.githubusercontent.com/10098613/229297938-5414b3e0-cc64-441a-8c0f-d28920b80dce.png)

[hp4195_8x13_remapped.yaff.txt](https://github.com/robhagemans/hoard-of-bitfonts/files/11129891/hp4195_8x13_remapped.yaff.txt)

**Comment by robhagemans** [comment]
Thanks! Note that you can achieve the automatic replacement in `yaff` by setting `default-char: 0x20`. But this works, too.
