### ISSUE TITLE
dec/type340.yaff - missing K

### ISSUE THREAD

**Issue by dan-jc-h** [robhagemans/hoard-of-bitfonts#30]
This font seems to have lost its `K`. Missing in both the `yaff` and `png`, so maybe a glitch in the source that it came from.

(no biggie for me, just browsing and probably won't use this font... just letting you know)

**Comment by robhagemans** [comment]
Good spot, thanks!

The site I got this from has the same issue, however the ultimate source is a datasheet that can be found here: http://bitsavers.org/pdf/dec/graphics/7-13_340_Display_Programming_Manual.pdf

I'll fix the glyphs based on this sheet. The 'A' is faulty as well and there also seems to be a non-standard character encoding.

**Comment by dan-jc-h** [comment]
Thank you - looks like you've tidied this up.  I'll leave it for you to close when you are happy with it.
